spring:
  application:
    name: e-commerce-basic


  # http://localhost:8080/oauth2/authorization/google
  # Datasource Configuration (Veritabanı Bağlantısı)
  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce_basic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}

upload:
  file:
    dir: /var/www/upload/ecommerce/
    url: https://litysofttest1.site/api/v1/upload/
    product:
      size: 10485760

cookie:
  refreshTokenCookie:
    secure: true
    refreshmaxAge: 604800
    sameSite: "Strict"
    path: /api/v1/auth

jwt:
  accessExp: 900000
  refreshAge: 604800000
  secret: C2VB987vxNVXvn543xVvxmVX7BCVM432NxvbvbnVXncm
  jwtheader: Authorization

regex:
  email: ^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$
  password: ^(?=.*[A-Z]).{8,}$

payment:
  iyzico:
    apiKey: sandbox-JbYzNd3TVSGRKgrKKFiM5Ha7MJP7YZSo
    secretKey: sandbox-mvXUSAUVAUhj7pNFFsbrKvWjGL5cEaUP
    baseUrl: https://sandbox-api.iyzipay.com
    callBack: /api/v1/payment/payCallBack

domain:
  test: https://litysofttest1.site